<?php
return [
    // Toimintaympäristö
    'environment'       => ['fi' => 'Toimintaympäristö', 'sv' => 'Driftsmiljö',      'en' => 'Operating environment', 'it' => 'Ambiente operativo', 'el' => 'Λειτουργικό περιβάλλον'],
    'environments'      => ['fi' => 'Toimintaympäristöt','sv' => 'Driftsmiljöer',    'en' => 'Operating environments','it' => 'Ambienti operativi', 'el' => 'Λειτουργικά περιβάλλοντα'],
    // Alue / laitos / osasto
    'zone'              => ['fi' => 'Alue / laitos',     'sv' => 'Område / anläggning','en' => 'Zone / area',          'it' => 'Zona / impianto',    'el' => 'Ζώνη / περιοχή'],
    'zones'             => ['fi' => 'Alueet / laitokset','sv' => 'Områden',           'en' => 'Zones',                'it' => 'Zone',               'el' => 'Ζώνες'],
    // Vaatimustasot
    'mandatory'         => ['fi' => 'Pakollinen',        'sv' => 'Obligatorisk',      'en' => 'Mandatory',            'it' => 'Obbligatorio',       'el' => 'Υποχρεωτικό'],
    'conditional'       => ['fi' => 'Ehdollinen',        'sv' => 'Villkorlig',        'en' => 'Conditional',          'it' => 'Condizionale',       'el' => 'Υπό όρους'],
    'prohibited'        => ['fi' => 'Kielletty',         'sv' => 'Förbjuden',         'en' => 'Prohibited',           'it' => 'Vietato',            'el' => 'Απαγορευμένο'],
    'information'       => ['fi' => 'Ohje / tiedoksi',   'sv' => 'Information',       'en' => 'Information',          'it' => 'Informazione',       'el' => 'Πληροφορία'],
    'not_applicable'    => ['fi' => 'Ei sovelleta',      'sv' => 'Ej tillämplig',     'en' => 'Not applicable',       'it' => 'Non applicabile',    'el' => 'Δεν εφαρμόζεται'],
    // Suojaimen luokat
    'personal_protection' => ['fi' => 'Henkilönsuojain','sv' => 'Personlig skyddsutrustning','en' => 'Personal protective equipment','it' => 'Dispositivo di protezione individuale','el' => 'Μέσο ατομικής προστασίας'],
    'other_safety'      => ['fi' => 'Muu turvallisuusvaruste','sv' => 'Övrig säkerhetsutrustning','en' => 'Other safety equipment','it' => 'Altro dispositivo di sicurezza','el' => 'Άλλος εξοπλισμός ασφαλείας'],
    // Hakuvaiheen otsikot
    'select_environment'=> ['fi' => 'Valitse toimintaympäristö', 'sv' => 'Välj driftmiljö',     'en' => 'Select environment',     'it' => 'Seleziona ambiente',         'el' => 'Επιλέξτε περιβάλλον'],
    'select_site'       => ['fi' => 'Valitse työmaa / toimipaikka','sv' => 'Välj arbetsplats',  'en' => 'Select site / workplace','it' => 'Seleziona cantiere',         'el' => 'Επιλέξτε εργοτάξιο'],
    'select_zone'       => ['fi' => 'Valitse alue / laitos',      'sv' => 'Välj område',        'en' => 'Select zone / area',     'it' => 'Seleziona zona',             'el' => 'Επιλέξτε ζώνη'],
    'select_task'       => ['fi' => 'Valitse työlaji / tehtävä',  'sv' => 'Välj arbetstyp',     'en' => 'Select job type / task', 'it' => 'Seleziona mansione',         'el' => 'Επιλέξτε είδος εργασίας'],
    'show_requirements' => ['fi' => 'Näytä vaatimukset',          'sv' => 'Visa krav',          'en' => 'Show requirements',      'it' => 'Mostra requisiti',           'el' => 'Εμφάνιση απαιτήσεων'],
    // Tulossivun osiot
    'section_always'    => ['fi' => 'A) Aina vaadittavat',        'sv' => 'A) Alltid obligatoriska','en' => 'A) Always required', 'it' => 'A) Sempre obbligatori',       'el' => 'Α) Πάντα απαιτούμενα'],
    'section_conditional'=> ['fi'=> 'B) Tilanteen mukaan',        'sv' => 'B) Situationsbetingat', 'en' => 'B) Situational',    'it' => 'B) In base alla situazione',  'el' => 'Β) Ανά περίσταση'],
    'section_other'     => ['fi' => 'C) Muut turvallisuusvarusteet','sv'=>'C) Övrig säkerhetsutrustning','en'=>'C) Other safety equipment','it'=>'C) Altri dispositivi di sicurezza','el'=>'Γ) Άλλος εξοπλισμός'],
    'section_critical'  => ['fi' => 'D) Kriittiset huomiot',      'sv' => 'D) Kritiska observationer','en'=> 'D) Critical notes','it'=> 'D) Note critiche',             'el' => 'Δ) Κρίσιμες παρατηρήσεις'],
    'section_attachments'=> ['fi'=> 'E) Ohjeet ja liitteet',      'sv' => 'E) Instruktioner och bilagor','en'=> 'E) Guides & attachments','it'=> 'E) Guide e allegati',  'el' => 'Ε) Οδηγίες και συνημμένα'],
    // Virallinen huomio
    'official_only'     => ['fi' => 'Vain sähköinen ohje on virallinen','sv'=>'Endast elektronisk instruktion är officiell','en'=>'Only the electronic guide is official','it'=>'Solo la guida elettronica è ufficiale','el'=>'Μόνο ο ηλεκτρονικός οδηγός είναι επίσημος'],
    'approved_version'  => ['fi' => 'Hyväksytyn version päiväys', 'sv' => 'Godkänd versionsdatum','en' => 'Approved version date','it' => 'Data versione approvata',   'el' => 'Ημερομηνία εγκεκριμένης έκδοσης'],
    // Lähde / periytyminen
    'source'            => ['fi' => 'Lähde',                      'sv' => 'Källa',               'en' => 'Source',                'it' => 'Fonte',                      'el' => 'Πηγή'],
    'condition'         => ['fi' => 'Ehto',                       'sv' => 'Villkor',             'en' => 'Condition',             'it' => 'Condizione',                 'el' => 'Προϋπόθεση'],
    'standard'          => ['fi' => 'Standardi',                  'sv' => 'Standard',            'en' => 'Standard',              'it' => 'Standard',                   'el' => 'Πρότυπο'],
    // Scope-tasot
    'scope_global'      => ['fi' => 'Yleinen vaatimus',           'sv' => 'Allmänt krav',        'en' => 'General requirement',   'it' => 'Requisito generale',         'el' => 'Γενική απαίτηση'],
    'scope_environment' => ['fi' => 'Toimintaympäristövaatimus',  'sv' => 'Krav för driftsmiljö','en' => 'Environment requirement','it' => 'Requisito ambiente',         'el' => 'Απαίτηση περιβάλλοντος'],
    'scope_site'        => ['fi' => 'Työmaakohtainen',            'sv' => 'Arbetsplatsspecifikt','en' => 'Site-specific',          'it' => 'Specifico del cantiere',     'el' => 'Ειδικό εργοταξίου'],
    'scope_zone'        => ['fi' => 'Aluekohtainen',              'sv' => 'Områdesspecifikt',    'en' => 'Zone-specific',          'it' => 'Specifico della zona',       'el' => 'Ειδικό ζώνης'],
    'scope_task'        => ['fi' => 'Tehtäväkohtainen',           'sv' => 'Arbetsuppgiftsspecifikt','en'=>'Task-specific',         'it' => 'Specifico del compito',      'el' => 'Ειδικό εργασίας'],
    'scope_site_task'   => ['fi' => 'Työmaa + tehtävä',           'sv' => 'Arbetsplats + uppgift','en' => 'Site + task',           'it' => 'Cantiere + compito',         'el' => 'Εργοτάξιο + εργασία'],
    'scope_zone_task'   => ['fi' => 'Alue + tehtävä',             'sv' => 'Område + uppgift',    'en' => 'Zone + task',           'it' => 'Zona + compito',             'el' => 'Ζώνη + εργασία'],
    'scope_phase'       => ['fi' => 'Työvaihe',                   'sv' => 'Arbetsmoment',        'en' => 'Work phase',            'it' => 'Fase di lavoro',             'el' => 'Φάση εργασίας'],
    'scope_exception'   => ['fi' => 'Hyväksytty poikkeus',        'sv' => 'Godkänt undantag',    'en' => 'Approved exception',    'it' => 'Eccezione approvata',        'el' => 'Εγκεκριμένη εξαίρεση'],
    // Työnkulku
    'draft'             => ['fi' => 'Luonnos',                    'sv' => 'Utkast',              'en' => 'Draft',                 'it' => 'Bozza',                      'el' => 'Πρόχειρο'],
    'review'            => ['fi' => 'Tarkastettavana',            'sv' => 'Under granskning',    'en' => 'Under review',          'it' => 'In revisione',               'el' => 'Υπό αναθεώρηση'],
    'approved'          => ['fi' => 'Hyväksytty',                 'sv' => 'Godkänd',             'en' => 'Approved',              'it' => 'Approvato',                  'el' => 'Εγκεκριμένο'],
    'published'         => ['fi' => 'Julkaistu',                  'sv' => 'Publicerad',          'en' => 'Published',             'it' => 'Pubblicato',                 'el' => 'Δημοσιευμένο'],
    'archived'          => ['fi' => 'Arkistoitu',                 'sv' => 'Arkiverad',           'en' => 'Archived',              'it' => 'Archiviato',                 'el' => 'Αρχειοθετημένο'],
    // Hallinnan välilehdet
    'tab_environments'  => ['fi' => 'Toimintaympäristöt',         'sv' => 'Driftsmiljöer',       'en' => 'Environments',          'it' => 'Ambienti',                   'el' => 'Περιβάλλοντα'],
    'tab_sites'         => ['fi' => 'Työmaat',                    'sv' => 'Arbetsplatser',       'en' => 'Sites',                 'it' => 'Cantieri',                   'el' => 'Εργοτάξια'],
    'tab_zones'         => ['fi' => 'Alueet',                     'sv' => 'Områden',             'en' => 'Zones',                 'it' => 'Zone',                       'el' => 'Ζώνες'],
    'tab_tasks'         => ['fi' => 'Työlajit',                   'sv' => 'Arbetstyper',         'en' => 'Job types',             'it' => 'Mansioni',                   'el' => 'Είδη εργασίας'],
    'tab_ppe'           => ['fi' => 'Suojainkirjasto',            'sv' => 'Skyddsutrustningsbibliotek','en' => 'PPE library',     'it' => 'Biblioteca DPI',             'el' => 'Βιβλιοθήκη ΜΑΠ'],
    'tab_rules'         => ['fi' => 'Vaatimussäännöt',            'sv' => 'Kravregler',          'en' => 'Requirement rules',     'it' => 'Regole di requisito',        'el' => 'Κανόνες απαιτήσεων'],
    'tab_audit'         => ['fi' => 'Audit-loki',                 'sv' => 'Granskningslogg',     'en' => 'Audit log',             'it' => 'Registro audit',             'el' => 'Αρχείο ελέγχου'],
    // Yleisiä
    'all_environments'  => ['fi' => 'Kaikki ympäristöt',          'sv' => 'Alla miljöer',        'en' => 'All environments',      'it' => 'Tutti gli ambienti',         'el' => 'Όλα τα περιβάλλοντα'],
    'all_sites'         => ['fi' => 'Kaikki työmaat',             'sv' => 'Alla arbetsplatser',  'en' => 'All sites',             'it' => 'Tutti i cantieri',           'el' => 'Όλα τα εργοτάξια'],
    'all_zones'         => ['fi' => 'Kaikki alueet',              'sv' => 'Alla områden',        'en' => 'All zones',             'it' => 'Tutte le zone',              'el' => 'Όλες οι ζώνες'],
    'all_tasks'         => ['fi' => 'Kaikki työlajit',            'sv' => 'Alla arbetstyper',    'en' => 'All job types',         'it' => 'Tutte le mansioni',          'el' => 'Όλα τα είδη εργασίας'],
    'no_zone'           => ['fi' => 'Ei aluerajausta',            'sv' => 'Inget område',        'en' => 'No zone filter',        'it' => 'Nessuna zona',               'el' => 'Χωρίς ζώνη'],
    // Vaatimussäännön hallinta
    'add_single_rule'   => ['fi' => '+ Lisää yksittäinen vaatimussääntö','sv' => '+ Lägg till enskild kravregeln','en' => '+ Add single requirement rule','it' => '+ Aggiungi regola requisito','el' => '+ Προσθήκη κανόνα'],
    'bulk_add_title'    => ['fi' => 'Massalisäys – lisää varuste usealle tehtävälle kerralla','sv' => 'Masslägga – lägg till utrustning för flera uppgifter','en' => 'Bulk add – add equipment to multiple tasks at once','it' => 'Aggiunta multipla','el' => 'Μαζική προσθήκη'],
    'bulk_add_desc'     => ['fi' => 'Valitse suojain, vaatimustaso ja kohde (työmaa/ympäristö). Sääntö lisätään kaikkiin kyseisen kohteen tehtäviin luonnoksena – tarkista ja julkaise sen jälkeen.','sv' => 'Välj skyddsutrustning, kravnivå och mål. Regel läggs till alla uppgifter som utkast.','en' => 'Select PPE, requirement level and target (site/environment). Rules are added to all tasks as drafts – review and publish afterwards.','it' => 'Seleziona DPI, livello di requisito e destinazione. Le regole vengono aggiunte come bozze.','el' => 'Επιλέξτε ΜΑΠ, επίπεδο απαίτησης και στόχο. Οι κανόνες προστίθενται ως πρόχειρα.'],
    'bulk_add_confirm'  => ['fi' => 'Lisätään varuste kaikille valitun kohteen tehtäville luonnoksena. Jatketaanko?','sv' => 'Utrustning läggs till alla uppgifter som utkast. Fortsätta?','en' => 'Equipment will be added to all tasks as drafts. Continue?','it' => 'Aggiungere come bozze a tutte le attività?','el' => 'Προσθήκη ως πρόχειρα σε όλες τις εργασίες;'],
    'confirm_archive_rule' => ['fi' => 'Arkistoi tämä sääntö?','sv' => 'Arkivera denna regel?','en' => 'Archive this rule?','it' => 'Archiviare questa regola?','el' => 'Αρχειοθέτηση αυτού του κανόνα;'],
    'add_equipment_to_task' => ['fi' => 'Lisää varuste tehtävälle','sv' => 'Lägg till utrustning för uppgiften','en' => 'Add equipment to task','it' => 'Aggiungi attrezzatura al compito','el' => 'Προσθήκη εξοπλισμού στην εργασία'],
    // Virheviestit
    'err_invalid_ppe'       => ['fi' => 'Valitse ensin suojain.','sv' => 'Välj en skyddsutrustning först.','en' => 'Please select a PPE item first.','it' => 'Seleziona prima un DPI.','el' => 'Επιλέξτε πρώτα ΜΑΠ.'],
    'err_no_tasks'          => ['fi' => 'Ei tehtäviä valitulle alueelle.','sv' => 'Inga uppgifter för det valda området.','en' => 'No tasks found for the selected area.','it' => 'Nessuna attività trovata.','el' => 'Δεν βρέθηκαν εργασίες.'],
    'err_upload_failed'     => ['fi' => 'Tiedoston lataus epäonnistui.','sv' => 'Filuppladdningen misslyckades.','en' => 'File upload failed.','it' => 'Caricamento file fallito.','el' => 'Αποτυχία μεταφόρτωσης αρχείου.'],
    'err_too_large'         => ['fi' => 'Tiedosto on liian suuri (max 2 MB).','sv' => 'Filen är för stor (max 2 MB).','en' => 'File is too large (max 2 MB).','it' => 'File troppo grande (max 2 MB).','el' => 'Το αρχείο είναι πολύ μεγάλο (max 2 MB).'],
    'err_invalid_type'      => ['fi' => 'Kuvaa ei hyväksytty – sallitut: SVG, JPG, PNG, WEBP.','sv' => 'Filen accepterades inte – tillåtna: SVG, JPG, PNG, WEBP.','en' => 'File not accepted – allowed: SVG, JPG, PNG, WEBP.','it' => 'File non accettato – permessi: SVG, JPG, PNG, WEBP.','el' => 'Μη αποδεκτό αρχείο – επιτρεπτά: SVG, JPG, PNG, WEBP.'],
    'err_move_failed'       => ['fi' => 'Tiedoston tallennus epäonnistui.','sv' => 'Det gick inte att spara filen.','en' => 'Failed to save the file.','it' => 'Impossibile salvare il file.','el' => 'Αποτυχία αποθήκευσης αρχείου.'],
    'err_missing_environment' => ['fi' => 'Valitulla työmaalla ei ole toimintaympäristöä. Lisää ympäristö ennen massalisäystä.','sv' => 'Vald arbetsplats saknar driftmiljö. Lägg till miljö före massläggning.','en' => 'Selected site has no environment. Add environment before bulk add.','it' => 'Il cantiere selezionato non ha ambiente. Aggiungi ambiente prima dell’inserimento multiplo.','el' => 'Το επιλεγμένο εργοτάξιο δεν έχει περιβάλλον. Προσθέστε περιβάλλον πριν τη μαζική προσθήκη.'],
    'bulk_add_success'      => ['fi' => 'Massalisäys onnistui: {count} sääntöä lisätty luonnoksina.','sv' => 'Masslägga lyckades: {count} regler tillagda som utkast.','en' => 'Bulk add succeeded: {count} rules added as drafts.','it' => 'Aggiunta multipla riuscita: {count} regole aggiunte come bozze.','el' => 'Μαζική προσθήκη επιτυχής: {count} κανόνες ως πρόχειρα.'],
    // UI card/modal improvements
    'task_cards'            => ['fi' => 'Tehtävät', 'sv' => 'Uppgifter', 'en' => 'Tasks', 'it' => 'Attività', 'el' => 'Εργασίες'],
    'search_select_filters_hint' => ['fi' => 'Valitse toimintaympäristö ja työmaa. Tehtäväkortit latautuvat automaattisesti alle.', 'sv' => 'Välj driftmiljö och arbetsplats. Uppgiftskort laddas automatiskt nedan.', 'en' => 'Select environment and site. Task cards load automatically below.', 'it' => 'Seleziona ambiente e cantiere. Le schede attività si caricano automaticamente sotto.', 'el' => 'Επιλέξτε περιβάλλον και εργοτάξιο. Οι κάρτες εργασιών φορτώνονται αυτόματα παρακάτω.'],
    'search_no_tasks'       => ['fi' => 'Ei tehtäviä näillä rajauksilla.', 'sv' => 'Inga uppgifter med dessa filter.', 'en' => 'No tasks with current filters.', 'it' => 'Nessuna attività con questi filtri.', 'el' => 'Δεν βρέθηκαν εργασίες με αυτά τα φίλτρα.'],
    'no_description'        => ['fi' => 'Ei kuvausta.', 'sv' => 'Ingen beskrivning.', 'en' => 'No description.', 'it' => 'Nessuna descrizione.', 'el' => 'Δεν υπάρχει περιγραφή.'],
    'open_task'             => ['fi' => 'Avaa tehtävä', 'sv' => 'Öppna uppgift', 'en' => 'Open task', 'it' => 'Apri attività', 'el' => 'Άνοιγμα εργασίας'],
    'count_mandatory'       => ['fi' => '{count} pakollista', 'sv' => '{count} obligatoriska', 'en' => '{count} mandatory', 'it' => '{count} obbligatori', 'el' => '{count} υποχρεωτικά'],
    'count_conditional'     => ['fi' => '{count} tilanteen mukaan', 'sv' => '{count} villkorliga', 'en' => '{count} conditional', 'it' => '{count} condizionali', 'el' => '{count} υπό όρους'],
    'count_other'           => ['fi' => '{count} muuta', 'sv' => '{count} övriga', 'en' => '{count} other', 'it' => '{count} altri', 'el' => '{count} άλλα'],
    'notes_and_risks'       => ['fi' => 'Huomiot ja riskit', 'sv' => 'Noteringar och risker', 'en' => 'Notes and risks', 'it' => 'Note e rischi', 'el' => 'Σημειώσεις και κίνδυνοι'],
    'risk'                  => ['fi' => 'Riski', 'sv' => 'Risk', 'en' => 'Risk', 'it' => 'Rischio', 'el' => 'Κίνδυνος'],
    'count_equipment'       => ['fi' => '{count} suojainta', 'sv' => '{count} skydd', 'en' => '{count} PPE items', 'it' => '{count} DPI', 'el' => '{count} ΜΑΠ'],
    'count_tasks'           => ['fi' => '{count} tehtävää', 'sv' => '{count} uppgifter', 'en' => '{count} tasks', 'it' => '{count} attività', 'el' => '{count} εργασίες'],
    'count_more_tasks'      => ['fi' => '+{count} lisää tehtäviä', 'sv' => '+{count} fler uppgifter', 'en' => '+{count} more tasks', 'it' => '+{count} attività in più', 'el' => '+{count} περισσότερες εργασίες'],
    'edit_task_title'       => ['fi' => 'Muokkaa tehtävää: {name}', 'sv' => 'Redigera uppgift: {name}', 'en' => 'Edit task: {name}', 'it' => 'Modifica attività: {name}', 'el' => 'Επεξεργασία εργασίας: {name}'],
    'edit_ppe_title'        => ['fi' => 'Muokkaa suojainta: {name}', 'sv' => 'Redigera skydd: {name}', 'en' => 'Edit PPE: {name}', 'it' => 'Modifica DPI: {name}', 'el' => 'Επεξεργασία ΜΑΠ: {name}'],
    'ppe_usage_title'       => ['fi' => 'Missä tehtävissä suojainta käytetään?', 'sv' => 'I vilka uppgifter används skyddet?', 'en' => 'Where is this PPE used?', 'it' => 'In quali attività viene usato questo DPI?', 'el' => 'Σε ποιες εργασίες χρησιμοποιείται αυτό το ΜΑΠ;'],
    'ppe_usage_notes_placeholder' => ['fi' => 'Esim. koskee kaikkia Siilinjärven tehtäviä', 'sv' => 'T.ex. gäller alla uppgifter i Siilinjärvi', 'en' => 'E.g. applies to all Siilinjärvi tasks', 'it' => 'Es. vale per tutte le attività di Siilinjärvi', 'el' => 'π.χ. ισχύει για όλες τις εργασίες του Siilinjärvi'],
    'link_to_selected_tasks' => ['fi' => 'Liitä valittuihin tehtäviin', 'sv' => 'Koppla till valda uppgifter', 'en' => 'Link to selected tasks', 'it' => 'Collega alle attività selezionate', 'el' => 'Σύνδεση με επιλεγμένες εργασίες'],
    'ppe_usage_hint'        => ['fi' => 'Jos et valitse yksittäisiä tehtäviä, suojain lisätään automaattisesti valitun ympäristön/työmaan tehtäville.', 'sv' => 'Om du inte väljer enskilda uppgifter läggs skyddet automatiskt till för vald miljö/arbetsplats.', 'en' => 'If no individual tasks are selected, PPE is automatically added to tasks in the chosen environment/site.', 'it' => 'Se non selezioni attività specifiche, il DPI viene aggiunto automaticamente alle attività dell’ambiente/cantiere scelto.', 'el' => 'Αν δεν επιλεγούν μεμονωμένες εργασίες, το ΜΑΠ προστίθεται αυτόματα στις εργασίες του επιλεγμένου περιβάλλοντος/εργοταξίου.'],
    'summary'               => ['fi' => 'Yhteenveto', 'sv' => 'Sammanfattning', 'en' => 'Summary', 'it' => 'Riepilogo', 'el' => 'Περίληψη'],
    'notes'                 => ['fi' => 'Huomio', 'sv' => 'Notering', 'en' => 'Note', 'it' => 'Nota', 'el' => 'Σημείωση'],
    'details'               => ['fi' => 'Lisätiedot', 'sv' => 'Mer info', 'en' => 'Details', 'it' => 'Dettagli', 'el' => 'Λεπτομέρειες'],
];
